apiVersion: v1
kind: Pod
metadata:
  name: devops-pod
  labels:
    app: devops-app
spec:
  containers:
    - name: devops-app
      image: devops-app
      imagePullPolicy: Never           # Use local Docker image (Minikube)
      ports:
        - containerPort: 5000
